ALTER TABLE s367550.app_user
    ADD COLUMN IF NOT EXISTS is_temp BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS temp_expires_at TIMESTAMPTZ;

UPDATE s367550.app_user
SET is_temp = COALESCE(is_temp, FALSE);
